#DB AWS-QA
AWS_TEST_Server =10.21.1.85
port = 1433
AWS_TEST_DB = caps
AWS_TEST_UserName = cfcautomationuser
AWS_TEST_Password = Zk4AaqhvygxOoNg72CDxVwWGPZEiZtnoh2sfTr7ApIa6Lig6XsXBiXQ0UG/r1CC3B9O7balSGyZ1h0+WDauhaA==
AWS_QA_Server = 10.21.5.252
AWS_QA_DB = caps
AWS_QA_UserName = cfcautomationuser
QA_UserName = cfcautomationuser
TEST_UserName = admin
AWS_QA_Password = BbZFQhOurCs2pIXWn1wwlfV15AavBMw3d25AE824uyuP57FdRMxQqw==

#DB ecs-Test
ECS_TEST_Server = ecs-sql-test
ECS_TEST_DB = mobile_app
ECS_TEST_UserName = cfcautomationuser
ECS_TEST_Password = 9w7fP0SKAFnNupMlbPFozakAyNWay9M0n9WVHXZ3qGQQ1dn0MSF+rQvuEZ0NgOg09FDrSG2oWT0tZveujUFhUw==
